var product = [{
    "id": 0,
    "title": "Select---",
    "image": "-",
    "price": "-",
    "brand": "-",
    "os": "-",
    "battery": "-",
    "model": "-",
    "storage": "-",
    "camera": "-",
    "RAM": "-",
    "g5": "-",
    "rr": "-",
    "weight": "-",
    "displaysize": "-",
    "displaytype": "-",
    "processor": "-",
    "date": "-",
    "sresolution": "-",
    "usbt": "-",
    "fastcharge": "-",
    "audiojack": "-",
    "fingerprint": "-",
    "fingerprintposition": "-",
    "faceu": "-",



},
{
    "id": 1,
    "title": "Samsung Galaxy Book2",
    "image": "https://static.toiimg.com/thumb/resizemode-4,msid-91544749,imgsize-200,width-600/91544749.jpg",
    "price": "88499",
    "brand": "Samsung",
    "os": "Intel",
    "battery": "5000 mAh",
    // "model": "A23",
    "storage": "512GB",
    // "camera": "50MP",
    "RAM": "8 GB",
    "g5": "Available",
    "rr": "60Hz",
    "weight": "500gm",
    "displaysize": "15.6 Inches",
    "displaytype": "LED",
    "processor": "Intel Core i5-1235U (12th Gen)	",
    // "date": "March 29, 2022 ",
    "sresolution": "1080x2408 pixels",
    "usbt": "USB Type-C 2.0",
    // "fastcharge": "25W fast charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    // "fingerprintposition": "Side FingerPrint",
    "faceu": "Yes",

}, {
    "id": 2,
    "title": "HP Victus 16 ",
    "image": "https://static.toiimg.com/thumb/resizemode-4,msid-82839477,imgsize-200,width-600/82839477.jpg",
    "price": "118999",
    "brand": "HP",
    "os": "Window 10",
    "battery": "5000 mAh",
    "model": "	16-e0075AX",
    "storage": "512GB",
    // "camera": "108MP",
    "RAM": "8GB",
    "g5": "Available",
    // "rr": "120Hz",
    "weight": "800gm",
    "displaysize": "6.6 inches (17.27 cm)",
    "displaytype": "Quad HD+ Dynamic AMOLED 2X Infinity-O",
    "processor": "Qualcomm SM8450 Snapdragon 8 Gen 1",
    "date": "February 25, 2022",
    "sresolution": "1440 x 3088 pixels",
    "usbt": "USB-C Type",
    "fastcharge": "45W fast charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Bottom Centre of the Screen.",
    "faceu": "Yes",

}, {
    "id": 3,
    "title": "Lenvo s145",
    "image": "https://static.toiimg.com/thumb/resizemode-4,msid-67465040,imgsize-200,width-600/67465040.jpg",
    "price": "15999",
    "brand": "Samsung",
    "os": "Android",
    "battery": "5000 mAh",
    "model": "F23 5G",
    "storage": "128GB",
    "camera": "50MP",
    "RAM": "4GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "198g",
    "displaysize": "16.76 cm (6.6 inch)",
    "displaytype": "Super AMOLED",
    "processor": "Qualcomm Snapdragon 750G processor",
    "date": "8th March 2022",
    "sresolution": "2408 x 1080 Pixels",
    "usbt": "USB Type C",
    "fastcharge": "25W Fast Charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Side Fingerprint",
    "faceu": "Yes",

}, {
    "id": 4,
    "title": " DELL Inspiron 16 ",
    "image": "https://static.toiimg.com/thumb/resizemode-4,msid-74495581,imgsize-200,width-600/74495581.jpg",
    "price": "15999",
    "brand": "DELL",
    "os": "WINDOW 11",
    "battery": "5020 mAh",
    // "model": "MI 10 Pro",
    "storage": "128GB",
    "camera": "64MP",
    "RAM": "6GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "192g",
    "displaysize": "16.9cm(6.67 inches)",
    "displaytype": "FHD+ Super AMOLED.",
    "processor": "Octa-core Qualcomm Snapdragon 732G processor",
    "date": "4th March 2021",
    "sresolution": "1080 x 2400 pixels",
    "usbt": "USB-C Type",
    "fastcharge": "33W Fast Charging ",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Side Fingerprint",
    "faceu": "Yes",

}, {
    "id": 5,
    "title": "Lenovo V15",
    "image": "https://static.toiimg.com/thumb/resizemode-4,msid-76521916,imgsize-200,width-600/76521916.jpg",
    "price": "₹42390",
    "brand": "Lenovo",
    "os": "Window 11",
    "battery": "5000 mAh",
    "model": "Intel Core i5-1035G1 (10th Gen)",
    "storage": "512GB",
    // "camera": "50MP",
    "RAM": "8GB",
    // "g5": "Available",
    // "rr": "120Hz",
    "weight": "1.85kg",
    "displaysize": "15.6 Inches (39.62 cm)",
    "displaytype": "FHD+",
    "processor": "15.6 Inches (39.62 cm)",
    "date": "March 16, 2022",
    "sresolution": "1080 x 2408 pixels",
    "usbt": "USB-C Type",
    "fastcharge": "18W fast charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Side Fingerprint",
    "faceu": "Yes",
}, {
    "id": 6,
    "title": "Dell Vostro 15",
    "image": "https://static.toiimg.com/thumb/resizemode-4,msid-71749908,imgsize-200,width-600/71749908.jpg",
    "price": "₹34244",
    "brand": "DELL",
    "os": "Window 11",
    "battery": "3095 mAh",
    "model": "15 3568 (A553117WIN9)",
    "storage": "256GB",
    // "camera": "12MP",
    "RAM": "6GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "2.2 kg",
    "displaysize": "15.6 inches (39.62 cm)",
    "displaytype": "LED",
    "processor": "Intel Core i3-7020U (7th Gen)",
    "date": "July 2013",
    "sresolution": "1366 x 768  pixels",
    "usbt": "USB-C type",
    "fastcharge": "30W Fast Charging",
    "audiojack": " 3.5mm",
    "fingerprint": "No Fingerprint Sensor",
    "fingerprintposition": "-",
    // "faceu": "Yes",
}, {
    "id": 7,
    "title": "Asus ROG Zenphyrus G14",
    "image": "https://static.toiimg.com/thumb/resizemode-4,msid-73219830,imgsize-200,width-600/73219830.jpg",
    "price": "	₹138,990 ",
    "brand": "Asus",
    "os": "Window 11",
    "battery": "4300 mAh",
    "model": "ROG Zephyrus G14 (2021)",
    "storage": "1TB",
    "SSD": "2TB",
    "RAM": "8GB",

    "rr": "90Hz",
    "weight": "1.7kg",
    "displaysize": "14.00-inch",
    "displaytype": "Full HD+ AMOLED Display",
    "processor": "	AMD Ryzen 7 5800HS",
    "date": " 26th May 2021",
    "sresolution": "2376 x 1080 Pixels",
    "usbt": "USB Type-C",
    "fastcharge": "44W Fast Charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    // "fingerprintposition": "On-screen Fingerprint Sensor",
    "faceu": "Yes",

},]