var product = [{
    "id": 0,
    "title": "Select---",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTLFG5jFe5HQXGP1z3HZrTYGRP0hA9My8iAg&usqp=CAU",
    "price": "-",
    "brand": "-",
    "os": "-",
    "battery": "-",
    "model": "-",
    "storage": "-",
    "camera": "-",
    "RAM": "-",
    "g5": "-",
    "rr": "-",
    "weight": "-",
    "displaysize": "-",
    "displaytype": "-",
    "processor": "-",
    "date": "-",
    "sresolution": "-",
    "usbt": "-",
    "fastcharge": "-",
    "audiojack": "-",
    "fingerprint": "-",
    "fingerprintposition": "-",
    "faceu": "-",



},
{
    "id": 1,
    "title": "Samsung Galaxy A23",
    "image": "https://m.media-amazon.com/images/I/91W42b8YW+L._SL1500_.jpg",
    "price": "18499",
    "brand": "Samsung",
    "os": "Android",
    "battery": "5000 mAh",
    "model": "A23",
    "storage": "128GB",
    "camera": "50MP",
    "RAM": "6GB",
    "g5": "Available",
    "rr": "60Hz",
    "weight": "195g",
    "displaysize": "16.76 cm (6.6 inch)",
    "displaytype": "PLS LCD",
    "processor": "Octa-core(EXYNOS)",
    "date": "March 29, 2022 ",
    "sresolution": "1080x2408 pixels",
    "usbt": "USB Type-C 2.0",
    "fastcharge": "25W fast charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Side FingerPrint",
    "faceu": "Yes",

}, {
    "id": 2,
    "title": "Samsung Galaxy Ultra S22",
    "image": "https://m.media-amazon.com/images/I/71J8tz0UeJL._SL1500_.jpg",
    "price": "118999",
    "brand": "Samsung",
    "os": "Android",
    "battery": "5000 mAh",
    "model": "S22",
    "storage": "512GB",
    "camera": "108MP",
    "RAM": "12GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "229g",
    "displaysize": "6.8 inches (17.27 cm)",
    "displaytype": "Quad HD+ Dynamic AMOLED 2X Infinity-O",
    "processor": "Qualcomm SM8450 Snapdragon 8 Gen 1",
    "date": "February 25, 2022",
    "sresolution": "1440 x 3088 pixels",
    "usbt": "USB-C Type",
    "fastcharge": "45W fast charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Bottom Centre of the Screen.",
    "faceu": "Yes",

}, {
    "id": 3,
    "title": "Samsung Galaxy F23",
    "image": "https://images.samsung.com/is/image/samsung/p6pim/in/sm-e236bidgins/gallery/in-galaxy-f23-4gb-ram-sm-e236bidgins-thumb-532475959?$240_240_PNG$",
    "price": "15999",
    "brand": "Samsung",
    "os": "Android",
    "battery": "5000 mAh",
    "model": "F23 5G",
    "storage": "128GB",
    "camera": "50MP",
    "RAM": "4GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "198g",
    "displaysize": "16.76 cm (6.6 inch)",
    "displaytype": "Super AMOLED",
    "processor": "Qualcomm Snapdragon 750G processor",
    "date": "8th March 2022",
    "sresolution": "2408 x 1080 Pixels",
    "usbt": "USB Type C",
    "fastcharge": "25W Fast Charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Side Fingerprint",
    "faceu": "Yes",

}, {
    "id": 4,
    "title": "Redmi Note 10 Pro",
    "image": "https://i02.appmifile.com/979_operator_in/12/08/2021/6e2a99cf7decf70d9e58a2871c1f19c0.png",
    "price": "15999",
    "brand": "Xiaomi",
    "os": "Android",
    "battery": "5020 mAh",
    "model": "MI 10 Pro",
    "storage": "128GB",
    "camera": "64MP",
    "RAM": "6GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "192g",
    "displaysize": "16.9cm(6.67 inches)",
    "displaytype": "FHD+ Super AMOLED.",
    "processor": "Octa-core Qualcomm Snapdragon 732G processor",
    "date": "4th March 2021",
    "sresolution": "1080 x 2400 pixels",
    "usbt": "USB-C Type",
    "fastcharge": "33W Fast Charging ",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Side Fingerprint",
    "faceu": "Yes",

}, {
    "id": 5,
    "title": "IQOO Z6 5G",
    "image": "https://in-exstatic-vivofs.iqoo.com/jCRQLfkJ0cXr10qJ/1647924041024/e21575e4c824bc3cd17748df494c0aef.png",
    "price": "14999",
    "brand": "IQOO",
    "os": "Android",
    "battery": "5000 mAh",
    "model": "Z6 5G",
    "storage": "128GB",
    "camera": "50MP",
    "RAM": "4GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "186g",
    "displaysize": "6.58 inches (16.71 cm)",
    "displaytype": "FHD+",
    "processor": "Snapdragon 695-6nm Processor",
    "date": "March 16, 2022",
    "sresolution": "1080 x 2408 pixels",
    "usbt": "USB-C Type",
    "fastcharge": "18W fast charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "Side Fingerprint",
    "faceu": "Yes",
}, {
    "id": 6,
    "title": "iPhone 13 Pro",
    "image": "https://m.media-amazon.com/images/I/61afOyd+zEL._AC_SL1500_.jpg",
    "price": "117900",
    "brand": "Apple",
    "os": "iOS",
    "battery": "3095 mAh",
    "model": "-",
    "storage": "256GB",
    "camera": "12MP",
    "RAM": "6GB",
    "g5": "Available",
    "rr": "120Hz",
    "weight": "204g",
    "displaysize": "6.1 inches (15.4 cm)",
    "displaytype": "Super Retina XDR OLED",
    "processor": "A15 Bionic processor",
    "date": "14th September 2021",
    "sresolution": "1170 x 2532 pixels",
    "usbt": "USB-C type",
    "fastcharge": "30W Fast Charging",
    "audiojack": " 3.5mm",
    "fingerprint": "No Fingerprint Sensor",
    "fingerprintposition": "-",
    "faceu": "Yes",
}, {
    "id": 7,
    "title": "Vivo V23 Pro",
    "image": "https://in-exstatic-vivofs.vivo.com/gdHFRinHEMrj3yPG/1641264341555/0787386c60d0b0fdc1f63fdb1f58c37b.png",
    "price": "38990",
    "brand": "Vivo",
    "os": "Android",
    "battery": "4300 mAh",
    "model": "V23 Pro",
    "storage": "128GB",
    "camera": "108MP",
    "RAM": "8GB",
    "g5": "Available",
    "rr": "90Hz",
    "weight": "171g",
    "displaysize": "16.66 cm (6.56 inch)",
    "displaytype": "Full HD+ AMOLED Display",
    "processor": "MediaTek Dimensity 1200",
    "date": "5th January 2021",
    "sresolution": "2376 x 1080 Pixels",
    "usbt": "USB Type-C",
    "fastcharge": "44W Fast Charging",
    "audiojack": "3.5mm",
    "fingerprint": "Yes",
    "fingerprintposition": "On-screen Fingerprint Sensor",
    "faceu": "Yes",

},]